from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/", defaults={"path": ""}, methods=["GET"])
@app.route("/<path:path>", methods=["GET"])
def index(path):
    return """{"movie":{"adult":false,"backdrop_path":"/rUEKdZ62hRbDNmrzrKy4KbH2lvI.jpg","belongs_to_collection":null,"budget":0,"genres":[{"id":18,"name":"Drama"},{"id":10770,"name":"TV Movie"}],"homepage":"","id":12443,"imdb_id":"tt0278017","original_language":"it","original_title":"Perlasca - Un eroe italiano","overview":"It is the real story of Giorgio Perlasca (Luca Zingaretti). During the 1920s he was an Italian Fascist supporter, fighting in Africa an in the Spanish civil war where he deserved a safe conduct for Spanish embassies. After some years, disillusioned by fascism, he is a fresh supplier for the Italian army. In the war years he is in Budapest for his business. He lives an easy life there, well introduced into the Hungarian high society, without any problem coming from the war situation. When the Nazi occupied Hungary, in 1944, instead to leave (Italy had already surrendered to the Allies) he escaped to the Spanish embassy in Budapest using his old safe conduct and becoming a Spanish citizen, changing name into Jorge Perlasca. He starts working as a diplomat here. When Sanz Briz (Geza Tordy), the Spanish consul, is removed, Perlasca immediately substitutes him, like if he was officially appointed from Spanish authorities... Written by 1felco","popularity":2.038,"poster_path":"/5b3CPtIvRwva6jZuhd6dHCuCcaS.jpg","production_companies":[{"id":1583,"logo_path":"/gKP4egMJOi5rksdnplfPV1wa0sd.png","name":"RAI","origin_country":"IT"},{"id":2999,"logo_path":"/zGSqFee9aDgDuLD6vcs2mcJUem4.png","name":"SVT","origin_country":"SE"},{"id":11359,"logo_path":"/aqWJRi66t2oMPMmC60CdK9I3WQd.png","name":"France 2","origin_country":"FR"},{"id":13799,"logo_path":null,"name":"Hamster Productions","origin_country":"FR"},{"id":54737,"logo_path":null,"name":"Focusfilm Kft.","origin_country":""},{"id":114560,"logo_path":null,"name":"Palomar-Endemol","origin_country":""}],"production_countries":[{"iso_3166_1":"SE","name":"Sweden"},{"iso_3166_1":"IT","name":"Italy"},{"iso_3166_1":"HU","name":"Hungary"},{"iso_3166_1":"FR","name":"France"}],"release_date":"2002-01-28","revenue":0,"runtime":126,"spoken_languages":[{"english_name":"Italian","iso_639_1":"it","name":"Italiano"}],"status":"Released","tagline":"","title":"Perlasca: The Courage of a Just Man","video":false,"vote_average":7.2,"vote_count":20}}"""

if __name__ == "__main__":
    app.run(port=9999)